
name: Python versions runner
on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Versions to build'
        required: true
      publish-releases:
        description: 'Whether to publish releases'
        required: true
        default: 'false'

defaults:
  run:
    shell: pwsh

jobs:
  process-inpit:
    runs-on: ubuntu-latest
    outputs:
      tool-versions: ${{ steps.split-input.outputs.tool-versions }}
    steps:
      - id: split-input
        name: Split input into array
        run: |
          $array = "${{ github.event.inputs.versions }}".split(",")
          Write-Host "::set-output name=tool-versions::${array}"

  trigger_builds:
    needs: process-inpit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ needs.process-inpit.outputs.tool-versions }}
    steps:
      - run: Write-Host "${{ matrix.version }}"