name: Python versions runner
on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Versions to build'
        required: true
      publish-releases:
        description: 'Whether to publish releases'
        required: true
        default: 'false'

defaults:
  run:
    shell: pwsh

jobs:
  trigger_builds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: '${{ fromJson(github.event.inputs.versions) }}'
    steps:
      - run: Write-Host "${{ matrix.version }}"