name: Test Powershell

# Controls when the workflow will run
on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: Write-Host $PSVersionTable
  windows:
    runs-on: windows-latest
    steps:
      - run: Write-Host $PSVersionTable
