
# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Python version to build and upload'
        required: true
      PUBLISH_RELEASES:
        description: 'Whether to publish releases'
        required: true
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.VERSION }}
        shell: pwsh
      - run: Start-Sleep -seconds 60
        shell: pwsh
