# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          uri="https://downloads.python.org/pypy/versions.json"
          toolsetVersions=("3.8" "3.7" "3.6" "2.7")

          for toolsetVersion in $toolsetVersions; do
              latestMajorPyPyVersion=$(curl $uri | jq --arg toolsetVersion $toolsetVersions '.[] | select((.python_version | contains($toolsetVersion)) and .stable == true).files[] | select(.arch == "x64" and .platform == "linux").download_url' | head -1)

              if [[ -z "$latestMajorPyPyVersion" ]]; then
                  echo "Failed to get PyPy version '$toolsetVersion'"
              fi

              echo "Installing '$latestMajorPyPyVersion'"
          done
