# This is a basic workflow to help you get started with Actions

name: Test Workflow

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [test-workflow-trigger]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.version }}
        shell: pwsh
      - run: Start-Sleep -seconds 20
        shell: pwsh
