# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows22:
    # The type of runner that the job will run on
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - run: git status
      - run: git --version
  windows19:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: git status
      - run: git --version
