# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Preview"
          $componentsToAdd = @(
            "Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.29.16.11.ARM",
            "Microsoft.VisualStudio.Component.VC.14.29.16.11.ARM.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.29.16.11.ARM64",
            "Microsoft.VisualStudio.Component.VC.14.29.16.11.ARM64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.29.16.11.x86.x64",
            "Microsoft.VisualStudio.Component.VC.14.29.16.11.x86.x64.Spectre"
          )
          [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -eq 0)
          {
              Write-Host "components have been successfully added"
          }
          else
          {
              Write-Host "components were not installed"
              exit 1
          }
